### ISSUE TITLE
在推理阶段，是否依然需要把class definition给出来

### ISSUE THREAD

**Issue by jiuerbujie** [ICT-GoKnow/KnowCoder#1]
![image](https://github.com/user-attachments/assets/f1d00961-f84e-4e17-8b18-d55fbd62073d)
请问，在推理阶段的数据构造中，实体是通过import引入的，但是PlaceOfBirth的关系依然在instruction里面写了一遍，PlaceOfBirth是否是必要的呢，如果这个PlaceOfBirth这个关系在训练数据中有，是否也可以直接import就可以了。

**Comment by yuxinzuo** [comment]
您好，图中右侧展示的关系抽取的Example，因此需要在指令中给定所有关系的类定义，而import的是类提示（Type Hint）中涉及的实体类。
